texts = ["The human brain is the central organ of the human nervous system, consisting of the cerebrum, cerebellum, and brainstem. It is located in the head, protected by the skull and close to the primary sensory organs for vision, hearing, taste, smell and touch. The brain has the same general structure as the brains of other mammals, but is more complex than any other known type of brain.",
         "A computer program is a set of instructions that a computer can interpret and execute. Programs are usually written in a high-level programming language, such as Python, C++, or Java, and then translated into machine code that a computer can understand. Programs can perform a wide range of tasks, from simple mathematical calculations to complex simulations and artificial intelligence applications.",
         "The solar system is the gravitationally bound system of the sun and the objects that orbit it, either directly or indirectly. Of the objects that orbit the sun directly, the largest are the eight planets, with the remainder being smaller objects, such as the five dwarf planets and small Solar System bodies. Of the objects that orbit the sun indirectly—the moons—two are larger than the smallest planet, Mercury.",
         "Artificial intelligence (AI) is the simulation of human intelligence processes by computer systems. These processes include learning (the acquisition of information and rules for using the information), reasoning (using the rules to reach approximate or definite conclusions), and self-correction. Particular applications of AI include expert systems, natural language processing, robotics, and vision.",
         "The Industrial Revolution was the transition to new manufacturing processes in Europe and the US, in the period from about 1760 to sometime between 1820 and 1840. This transition included going from hand production methods to machines, new chemical manufacturing and iron production processes, improved efficiency of water power, the increasing use of steam power, and the development of machine tools. It also led to social, economic, and cultural changes.",
         "The field of genetics is the study of genes, genetic variation, and heredity in living organisms. The discipline of genetics has a number of subfields, including classical genetics, molecular genetics, population genetics, developmental genetics, and evolutionary genetics. Advances in genetics have led to a greater understanding of inherited diseases and the development of gene therapies, and have also contributed to the development of new crops and livestock through genetic engineering.",
         "The theory of evolution by natural selection, first proposed by Charles Darwin and Alfred Russel Wallace in 1858, is the process by which populations of living organisms change over time in response to changes in their environment. This process leads to the development of new species through a process of speciation, and the extinction of existing species. The theory of evolution is supported by a wealth of scientific evidence, including the fossil record, comparative anatomy and biochemistry, and the study of genetic variation.",
         "Quantum mechanics is the branch of physics that deals with the behavior of particles on a very small scale, such as atoms and subatomic particles. Quantum mechanics is based on the principles of wave-particle duality, which states that particles can exhibit both wave-like and particle-like properties depending on how they are observed. This theory has led to a better understanding of phenomena such as quantum entanglement, superposition, and the uncertainty principle. It also plays a crucial role in technologies such as transistors, lasers and the computer.",
]
